### PR TITLE
Gh 103 refactor to versioned services

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary

Refactoring the SDK to have a package for each version per service. This will allow us to easily incorporate generated abstractions and allow the user to use packages specific to service version. This is a breaking change and once we have generated the Discovery service, we will incorporate all generated abstractions and release as 1.0.0.

### CODE REVIEW

**Comment by mediumTaj** [comment]
@atilatosta I refactored the SDK to have versioned services. Can you take a look when you have a chance, please?

**Comment by mediumTaj** [comment]
By the way, the actual version of this SDK will be `1.0.0` since it is a breaking change. I will version up once Discovery is complete and I add all generated services.

**Comment by atilatosta** [comment]
@mediumTaj hey man! I'm evaluating and I have some doubts, let's talk, okay?

**Comment by mediumTaj** [comment]
@atilatosta Yes, find me on slack when you get a chance. It would be good to list the issues with the refactor here as well.

**Pull request merged**
