### PR TITLE
Update to VS 2017

### PR DESCRIPTION
**Pull request by Franklin89**
Not sure if this is interesting for you guys. But I just updated all the projects to the new structure that uses `csproj` files again.

### CODE REVIEW

**Comment by mediumTaj** [comment]
Does this fix any existing issues or is this transitioning the SDK to vs 2017?

**Comment by Franklin89** [comment]
No it does not fix any issues. Just transitioning, but it in my opinion it makes it more readable and will work better with the latest version of the dotnet tooling.

**Comment by mediumTaj** [comment]
OK. @atilatosta what do you think?

**Comment by atilatosta** [comment]
@mediumTaj i'll check it.

@Franklin89 thank's!

**Comment by Franklin89** [comment]
@atilatosta Using Visual Studio! It automatically migrates the `project.json` and the `*.xproj`. Then I ran all the unit tests and checked the changes.

**Comment by germanattanasio** [comment]
hey @Franklin89 Thanks for the PR, do you think you can update it and fix the merge conflicts?

**Comment by Franklin89** [comment]
@germanattanasio uh wow, there has been some changes lately...but yeah sure i will do so.

**Comment by mediumTaj** [comment]
@Franklin89 don’t worry about this - there were some issues with the tests and I have resolved it in a separate branch with several more changes.

**Comment by mediumTaj** [comment]
Closing in favor of https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/180

**Pull request closed without merging**
