### PR TITLE
chore(User-Agent): Updated user-agent to include environment information

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary
This pull request adds environment info to the user-agent header. I also added `X-IBMCloud-SDK-Analytics` header to each operation.

`User-Agent` `watson-apis-dotnet-sdk-2.13.0 MicrosoftWindows 10.0.17134 .NETCore4.6.25211.02`

### CODE REVIEW

**Comment by ehdsouza** [comment]
@mediumTaj could you give an example value of how the user agent looks like?

**Comment by mediumTaj** [comment]
`watson-apis-dotnet-sdk/2.13.0 Microsoft Windows 10.0.17134 .NET Core 4.6.25211.02`

**Comment by mediumTaj** [comment]
Revised formatting of the header. 
`watson-apis-dotnet-sdk-2.13.0 MicrosoftWindows 10.0.17134 .NETCore4.6.25211.02`

@ehdsouza will this work?

**Pull request merged**
