### PR TITLE
- Change MessageRequest (Input/Context) to dynamic

### PR DESCRIPTION
**Pull request by maykonsIBM**
- Change MessageResponse(Input/Context) to dynamic
- Add methods in Interface

#85

### CODE REVIEW

**Comment by maykonsIBM** [comment]
Done @atilatosta

**Comment by claytonbnu** [comment]
The fix for this issue existed in version 0.2, but not 1.0.
Have a reason?

**Comment by atilatosta** [comment]
@claytonbnu Yes! The services are being generated through swagger, which must have overwritten.

@mediumTaj  Please, could you check this?

**Comment by mediumTaj** [comment]
@claytonbnu @atilatosta I will create an issue to support this in the codegen.

**Pull request merged**
