### PR TITLE
Add support for Conversation

### LINKED ISSUE #10: [conversation] Abstract Conversation service.
Abstract the `Conversation` service into the `dotnet-standard-sdk`
- [ ] Abstract service
- [ ] Add inline documentation
- [ ] Add service examples to readme
- [ ] Add unit tests
- [ ] Add integration tests

### PR DESCRIPTION
**Pull request by maykonsIBM**
### Summary

Added conversation services abstraction.
Added Integration Service.
Added Unit Test.

This pull requests fixes #10

### CODE REVIEW

**Comment by germanattanasio** [comment]
@maykonsIBM for Conversation we want the `context to be a key-value / dictionary/ map
Here is how the Java SDK represents a response from Conversation

```java
public class MessageResponse extends GenericModel {
  private static final String TEXT = "text";

  private Map<String, Object> context;
  private List<Entity> entities;
  private List<Intent> intents;
  private Map<String, Object> output;
  private Map<String, Object> input;

}
```

As you can see `context` is a dictionary. key-value.

I know this is not very OOP but the service team keeps updating what they return and if we enforce a rigid set of object we will end up  with a lot of code to manage the different `version_date`s

**Comment by atilatosta** [comment]
@germanattanasio I have a doubt. Analysing the Conversation documentation the Context in MessageResponse is one to one. So is it neccessary to be a Map/Dictionary? In c# there is a Tuple class, where we can create a data structure that has a specific number and sequence of elements, for example:
```cs
Tuple<string, Object> context { get; set; }
```
Look [Tuple Class](https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx)

Even so, the Conversation class has the id of conversation and the SystemResponse, in this case you are suggesting that the type is Object, as well as the Input and Output. But how we will deserialize it?

**Comment by germanattanasio** [comment]
I don't know C# that much @atilatosta. I do know we should use something that allows us to move from JSON to a data structure without imposing a fixed structure to the JSON

**Comment by mediumTaj** [comment]
@atilatosta @germanattanasio I'm also trying to figure this out for Unity. We don't have access to the Tuple class. We use [FullSerializer](https://github.com/jacobdufault/fullserializer) for serialization and deserialization. It can auto parse simple stuff like `Dictionary<string, string>` but anything complicated won't work.

**Comment by atilatosta** [comment]
@germanattanasio, @mediumTaj and @maykonsIBM what do you guys think to use the dynamic type? For example:
```c#
[JsonProperty("context")]
public dynamic Context { get; set; }
```
But I don't know how it will deserialized.

@maykonsIBM please, could you take a test?

**Comment by maykonsIBM** [comment]
I made the change in `MessageResponse` changing the `Context` to `dynamic`.

I ran IT, it worked normally.

untitled

**Comment by mediumTaj** [comment]
So will we be able to make the DataModel more generic?

**Comment by maykonsIBM** [comment]
@germanattanasio @mediumTaj Guys, I changed the types to dynamic, according to the test requested by @atilatosta

**Comment by mediumTaj** [comment]
Beautiful, thanks @maykonsIBM !

**Pull request merged**
