### PR TITLE
Corrected param case when instantiating config

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary
This pull request updates case for parameters when instantiating an authConfig in the readme.

### CODE REVIEW

**Comment by lpatino10** [comment]
I just looked in the .NET core and it looks to me like the parameters are uppercased like you had them before. Am I looking at something wrong?

**Comment by mediumTaj** [comment]
Yeah those are incorrect as well. Submitting a PR for that shortly

**Comment by mediumTaj** [comment]
Oh sorry, I thought you were referring to the readme! Yeah the fields are capitalized but the fields dib't have exposed setters. We initialize the configs via constructor
```
https://github.com/IBM/dotnet-sdk-core/blob/master/src/IBM.Cloud.SDK.Core/Authentication/Iam/IamConfig.cs#L73
```
```cs
IamConfig(string apikey = null, string iamUrl = null, string userManagedAccessToken = null, bool? disableSslVerification = null, string iamClientId = null, string iamClientSecret = null)
```

The convention is lowerCamelCase for method params.

**Pull request merged**
